### ISSUE TITLE
How many arguments does fgets() require?

### ISSUE THREAD

**Issue by maalos** [Velko/FsLibc#3]
How many arguments does fgets() require?
I can see that it requires 3, but I have no idea what could they be except of the stream.

**Comment by maalos** [comment]
nevermind, found it in tests.

**Comment by maalos** [comment]
uhm, something isn't right here
```c
void kernel_main(void) {
	terminal_initialize();
	FSLC_FILE stream;
	char cmd[10];
        char *str = fgets(cmd, 10, &stream);
	printf(cmd);
}
```

qemu just restarts after booting up

**Comment by Velko** [comment]
It does not work, because your stream is not set up for input. You should implement a function that can read a single character from whatever hardware you want to read it from and then tell FsLibc to use that.

If your code still resembles one as left off in #2, you could re-use scr_term for that.

First, add somewhere above `terminal_initialize()` function:
```C
int keyboard_getc(FILE *)
{
    //TODO: read and return a character from keyboard
}
```

Find the place where it says
```C
scr_term.putc = screen_putc;
stdin = stdout = &scr_term;
```

and change it to:
```C
scr_term.putc = screen_putc;
scr_term.getc = keyboard_getc;
scr_term.ungetc_buf = -1;
stdin = stdout = &scr_term;
```

You should be able to use `fgets` and other input functions. For example:
```C
char buffer[10];
fgets(buffer, 10, stdin);
```

FsLibc is now set up for input, but now the "fun" part - you should implement the `keyboard_getc()` to wait until a key is pressed and return the typed character. Or if you want something something easier - rename it to `serial_getc()` and read it from serial port. For quick example I should point you to [OsDev Wiki|Serial Ports](https://wiki.osdev.org/Serial_Ports). Unfortunately I'm not aware of any simple polling keyboard input driver code. Everybody seems to implement an interrupt based one, but getting that to work does not feel realistic at least for now.

**Comment by maalos** [comment]
for an assembly noob like me writing an interrupt-based kb driver one was a TODO a few days ago, when I assumed that there are none freestanding C libs... but i probably could read only a single char and then i would be trying to get it all to memory or sth else and mess around with it... anyways, i'm gonna try what you typed here and let you know in a sec.

**Comment by maalos** [comment]
```
Compiling kernel...
src/kernel/kernel.c: In function 'keyboard_getc':
src/kernel/kernel.c:49:1: error: parameter name omitted
 int keyboard_getc(FILE *)
 ^~~
```

**Comment by maalos** [comment]
and also, do i have to write the contents of keyboard_getc myself? or does that int just set it all up?

**Comment by Velko** [comment]
Ok, you can probably use
```C
int keyboard_getc(FILE *stream)
```
Sometimes compilers complain about unused parameters. Omitting the name is a way to say to compiler "it's Ok, it will be passed when called, but I'm not going to use it", but apparently your compiler gets confused.

And yes, you need to implement `keyboard_getc()` yourself. FsLibc does not have any logic to deal with underlying hardware. It provides only the platform-independent part of I/O. For actual communication you have to provide those `getc()` and `putc()` functions.

**Comment by maalos** [comment]
so, all the code u provided sets up everything but isn't capable of reading? if that's the case, i could maybe commit to the repo and add some functionality

**Comment by Velko** [comment]
There are thousands of combinations how one could want to use the I/O. What if one wanted to use it on Raspberry Pi? All x86-related code would be useless. Or send output to printer. Or ...

FsLibc was designed to be lean and do the "boring" parts of the communication - formatting and parsing. Those work the same way on every platform. If it included the actual hardware drivers, we may need to support lots of platforms and devices. An keeping it all in order can quickly grow into huge task. Not sure I want that.

That being said, I think there is a place for "Beginner OsDev Support" library, that could provide simple drivers for dozen or so most popular I/O platforms/devices. But that should be independent from FsLibc.

As for keyboard, I think it should be possible to implement a simple interrupt-less driver. Actually - I think I'll play around a bit, will see how it goes.

**Comment by Velko** [comment]
> Omitting the name is a way to say to compiler "it's Ok, it will be passed when called, but I'm not going to use it"
Sorry, appeard that was in some other language, not C

The keyboard driver turned out to be simpler than I thought. [Here](https://gist.github.com/Velko/6a1744997450496db1c28e40b2d4a896) it is.

**Comment by maalos** [comment]
so, just delete the previous declaration and include it? thats what i did, this happens:
```
Linking object files...
output/kernel/kernel.o: In function `keyboard_getc':
kernel.c:(.text+0xa6): undefined reference to `io_port8_read'
kernel.c:(.text+0xb7): undefined reference to `io_port8_read'
collect2: error: ld returned 1 exit status
```

**Comment by Velko** [comment]
There's a comment in file:
```C
/* Should be implemented in assembly,
    sometimes called as inb() and outb()
 */
uint8_t io_port8_read(uint16_t port);
void io_port8_write(uint16_t port, uint8_t value);
```
These are I/O port read/write functions which should be implemented in assembly. It is a very low level hardware access operation, that can not be abstracted in C.

Actually you need only first one. When you look for samples, it may be called `inb()` or `inportb()` or similar, but in my code I like to give more descriptive names. The important thing, however, is that name defined in assembly is same as used in C.

**Comment by maalos** [comment]
soo, if i got it right, i just have to write a func in asm here?

**Comment by Velko** [comment]
Yes. You need to write a function that loads the parameter into DX, executes IN instruction, reading value from I/O port into AL, and then returns.

**Comment by Velko** [comment]
BTW. If you're stuck, check that [Gist](https://gist.github.com/Velko/6a1744997450496db1c28e40b2d4a896) again 😉

**Comment by maalos** [comment]
thanks, i wasn't really stuck, i just put my os in C project onto the side and experimented with my fresh ASM skills and I'm trying to make a simple shell kernel. will definitely check it all out in action soon.
