### ISSUE TITLE
ld.lld: error: undefined symbol: sprintf

### ISSUE THREAD

**Issue by leap0x7b** [Velko/FsLibc#4]
I'm using this libc for my OS and got this error:
```
ld.lld: error: undefined symbol: sprintf
>>> referenced by kernel.c:75
>>>               ../../build/kernel/./kernel.o:(kprintf)
>>> did you mean: fprintf
>>> defined in: ../../build/libc/libc.a
```

**Comment by Velko** [comment]
Are you trying to use sprintf() function to implement your kprintf() ?

Unfortunately sprintf() is not implemented by FsLibc, all available routines are listed in README.

I suggest to rethink your kprintf() implementation, there's a good chance you do not have to use sprintf() at all. FsLibc I/O requires you to implement a function that prints single character to the screen (serial port or wherever). Why not just do that?

In case you still insist on using sprintf(), you have to make it yourself. [Here's an example](https://gist.github.com/Velko/f060c1724acc13b4f66157091db055af). It's not very well tested, so no guarantees. Good luck!

P.S. I might include sprintf() in core FsLibc some day, but do not keep your hopes too high.

**Comment by leap0x7b** [comment]
Thanks
